In [22]:
import pandas as pd
import helper.helpers as hp
import importlib
import warnings
warnings.filterwarnings('ignore')

importlib.reload(hp)

In [2]:
outside_data_root = './data/outside_concept/'

In [3]:
food_concepts = pd.read_csv(outside_data_root + 'CLAIMS_7_years_HUMAN FOOD_data.csv')
us_food_concepts = pd.read_excel(outside_data_root + 'us_food_for_synthetic.xlsx')

In [4]:
us_food_concepts.head()

,CAT1,CAT2,CAT3,RelIndex,RelFlag,RelWinRate,DiffIndex,DiffFlag,DiffWinRate,BelIndex,BelFlag,BelScore,ConceptText
0,HUMAN FOOD,NaN,NaN,109.754017,H,0.308333,133.496406,H,0.421667,110.201781,MH,0.940000,[Language:en-us=>New Oat-Based Chips This oat-...
1,HUMAN FOOD,NaN,NaN,99.262523,MH,0.285235,114.260294,M,0.328859,112.515027,H,0.959732,"[Language:en-us=>Introducing Grey Poupon, Bist..."
2,HUMAN FOOD,NaN,NaN,85.138958,ML,0.211667,110.138750,M,0.306667,109.420208,MH,0.933333,[Language:en-us=>Introducing Grey Poupon Reser...
3,HUMAN FOOD,NaN,NaN,83.171979,ML,0.210000,118.496094,MH,0.351667,103.167625,M,0.880000,"[Language:en-us=>Introducing Kraft Black Mayo,..."
4,HUMAN FOOD,NaN,NaN,83.514062,ML,0.203333,124.686719,H,0.385000,100.822906,M,0.860000,[Language:en-us=>Introducing Kraft Spread &#38...

In [42]:

mask = (~food_concepts['ConceptText'].isna()) & (food_concepts['Country']=='United States')
food_concepts = food_concepts.loc[mask]

In [43]:
food_concepts.drop(['CE_MostRelevant', 'CE_LeastRelevant',
       'CE_EspeciallyDifficult', 'CE_NewAndDifferent', 'CE_WordCode'], axis=1, inplace=True)
food_concepts['ConceptText'] = food_concepts['ConceptText'].apply(lambda x: hp.extract_concept_info(x))


food_concepts['CAT2'] = food_concepts['CAT2'].apply(lambda x: hp.clean_category_name(x) if not pd.isna(x) else x)
food_concepts['CAT3'] = food_concepts['CAT3'].apply(lambda x: hp.clean_category_name(x) if not pd.isna(x) else x)

In [47]:
food_concepts['CAT3'].isna().sum()

np.int64(3640)

In [51]:
# save the cleaned data 
food_concepts.to_excel(outside_data_root + 'cleaned_food_concepts.xlsx', index=False)

# for us_food

In [27]:
us_food_concepts = pd.read_excel(outside_data_root + 'us_food_for_synthetic.xlsx')

In [28]:
len(us_food_concepts)

10787

In [29]:
# filter only english ones 
eng_mask = us_food_concepts['ConceptText'].apply(lambda x: hp.is_english_simple(x))
us_food_concepts = us_food_concepts.loc[eng_mask]

In [30]:
len(us_food_concepts)

8037

In [31]:
us_food_concepts['ConceptText'] = us_food_concepts['ConceptText'].apply(lambda x: hp.extract_concept_info(x))

us_food_concepts['CAT2'] = us_food_concepts['CAT2'].apply(lambda x: hp.clean_category_name(x) if not pd.isna(x) else x)
us_food_concepts['CAT3'] = us_food_concepts['CAT3'].apply(lambda x: hp.clean_category_name(x) if not pd.isna(x) else x)

In [33]:
us_food_concepts.to_excel(outside_data_root + '0407_cleaned_us_food_concepts.xlsx', index=False)

,CAT1,CAT2,CAT3,RelIndex,RelFlag,RelWinRate,DiffIndex,DiffFlag,DiffWinRate,BelIndex,BelFlag,BelScore,ConceptText
0,HUMAN FOOD,NaN,NaN,109.754017,H,0.308333,133.496406,H,0.421667,110.201781,MH,0.940000,New Oat-Based Chips This oat-based snack is sa...
1,HUMAN FOOD,NaN,NaN,99.262523,MH,0.285235,114.260294,M,0.328859,112.515027,H,0.959732,"Introducing Grey Poupon, Bistro Sandwich Sauce..."
2,HUMAN FOOD,NaN,NaN,85.138958,ML,0.211667,110.138750,M,0.306667,109.420208,MH,0.933333,"Introducing Grey Poupon Reserve Mustards, a ra..."
3,HUMAN FOOD,NaN,NaN,83.171979,ML,0.210000,118.496094,MH,0.351667,103.167625,M,0.880000,"Introducing Kraft Black Mayo, a smooth and cre..."
4,HUMAN FOOD,NaN,NaN,83.514062,ML,0.203333,124.686719,H,0.385000,100.822906,M,0.860000,"Introducing Kraft Spread &#38 Crunch, a one-o..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10782,HUMAN FOOD,Salty snacks & appetizers,Dry savory snacks & chips,100.833759,MH,0.251149,121.272526,MH,0.381792,113.729658,H,0.962500,Cheetos Cheddar Jalapeno Crackers 9oz box for ...
10783,HUMAN FOOD,Salty snacks & appetizers,Dry savory snacks & chips,98.018182,MH,0.227424,122.718193,MH,0.385108,109.298632,MH,0.925000,Cheetos Cheese Pizza Crackers 9oz box for $3.8...
10784,HUMAN FOOD,Salty snacks & appetizers,Dry savory snacks & chips,97.634607,MH,0.224387,118.295998,MH,0.361544,110.775641,MH,0.937500,Cheetos Chipotle Ranch Crackers 9oz box for $3...
10785,HUMAN FOOD,Salty snacks & appetizers,Dry savory snacks & chips,97.112653,MH,0.220734,117.879754,MH,0.360652,103.390598,M,0.875000,Cheetos Smoked Cheddar Crackers 9oz box for $3...
10786,HUMAN FOOD,Salty snacks & appetizers,Dry savory snacks & chips,102.679674,H,0.265821,120.988670,MH,0.377006,107.821624,MH,0.912500,Cheetos White Cheddar Crackers 9oz box for $3....